main: com.lauriethefish.betterportals.BetterPortals
name: BetterPortals
version: 0.57
author: lauriethefish@outlook.com
api-version: 1.13
softdepend: [Multiverse-Core]

commands:
  betterportals:
    description: Main plugin command
    aliases:
      - bp

permissions:
  betterportals.reload:
    description: Allows you to use /bp reload
    default: op
  betterportals.wand:
    description: Allows you to get the portal wand with /bp wand
    default: op
  betterportals.select:
    description: Allows you to use /bp origin and /bp destination
    default: op
  betterportals.link:
    description: Allows you to create portals with /bp link
    default: op
  betterportals.remove:
    description: Allows you to remove portals that you created
    default: op
  betterportals.remove.others:
    description: Allows you to remove nether portals, as well as other portals not created by you
    default: op
