main: com.lauriethefish.betterportals.BetterPortals
name: BetterPortals
version: 0.22
author: lauriethefish@outlook.com
api-version: 1.13
softdepend: [Multiverse-Core]

#commands:
#  fakedeleteentity:
#    description: Testing command for the EntityManipulator
#  multiblockchangetest:
#    description: Testing command
