main: com.lauriethefish.betterportals.BetterPortals
name: BetterPortals
version: 0.42
author: lauriethefish@outlook.com
api-version: 1.13
softdepend: [Multiverse-Core]

commands:
  betterportals:
    description: Main plugin command
    aliases:
      - bp
