main: com.lauriethefish.betterportals.bukkit.BetterPortals
name: BetterPortals
version: 0.10.0
author: lauriethefish@outlook.com
api-version: 1.13
softdepend: [Multiverse-Core]
depend: [ProtocolLib]

commands:
  betterportals:
    description: Main plugin command
    aliases:
      - bp
#  stresstest:
#    description: Testing command used for performance testing

permissions:
  betterportals.reload:
    description: Allows you to use /bp reload
    default: op
  betterportals.wand:
    description: Allows you to get the portal wand with /bp wand
    default: op
  betterportals.select:
    description: Allows you to use /bp origin and /bp destination
    default: op
  betterportals.link:
    description: Allows you to create portals with /bp link
    default: op
  betterportals.linkexternal:
    description: Allows you to run /bp linkexternal to create cross-server portals.
  betterportals.remove:
    description: Allows you to remove portals that you created
    default: op
  betterportals.remove.others:
    description: Allows you to remove nether portals, as well as other portals not created by you
    default: op
  betterportals.reconnect:
    description: Allows you to use the /bp reconnect command
    default: op
  betterportals.see:
    description: Required for any player to see portals
    default: true
  betterportals.use:
    description: Required for any player to use portals
    default: true
  betterportals.setname:
    description: Allows you to set the name of portals
    default: op
  betterportals.setname.others:
    description: Allows you to set the name of portals that you didn't create
    default: op
  betterportals.getname:
    description: Allows you to use /bp getname
    default: op